# Generated by Django 4.2 on 2024-10-03 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='ratings_count',
            field=models.IntegerField(default=0, verbose_name='Количество оценок'),
        ),
        migrations.AddField(
            model_name='cat',
            name='ratings_score',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2, verbose_name='Оценка')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cat.cat', verbose_name='Котенок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'unique_together': {('cat', 'user')},
            },
        ),
    ]
