# Generated by Django 4.2 on 2024-10-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_cat_ratings_count_cat_ratings_score_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='Оценка'),
        ),
    ]
